@rillion_HostAddress = http://localhost:5192

### register
POST {{rillion_HostAddress}}/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Mysecretp@ssw0rd"
}

### login
POST {{rillion_HostAddress}}/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Mysecretp@ssw0rd"
}

### test the token
GET {{rillion_HostAddress}}/manage/info
Accept: application/json
Authorization: Bearer CfDJ8PvtjQMCay1Fm5RgD3Fa7zb7L2JR-ZrtVYsaJ45YVmXBXjIvNeHhRc44wGq7eVtbwyidtDw6qv1G5AUieXhWas9PuBEzfMuFLDRzPxmWTEHfZIFm0OsCYzDX1BHFAS_2taOODpcnjeFhnv7ARDwCRfHsihqEOEbUU40tZbO9IllAHZq1EOVlllCuwR0spbFJh4w9UVl1fs4OMjEnYeLvCNppX_4yeScbODBmSeXFKUfRcMzvSaLq5vECIWAoLiv0Ao6Zv_B3WCRzjF9hDDaKFafzkt2PXX-UIQMmTatdMBe7OMyzC431mgQrHI983iDcBjy-8fl9CsyBJxWONCJ16E1L8a_ryWyC-eyvve-kbIDf-WgDiSdIwu1g4lnLlSnJ6p5-wThuiuYNeT-LhKJpCoe_VD27H0ni8LxqAHY7OWEzgjr54MabrSnvWQvFRKFMA7cNF73dsf5Vvw4n8MPcrXU3YizKva6AnkAjYrDOALSNLe6eMTz2KqWe5wf6Ie-IW2K2wF9IO1zP0MlrkuN2xCPqbahqv5SbbXx0xwLjWJWwEdRVysaoGZTqHw9jZkOGdGKaB_fZphEgMjkUn9uv_GEQsTJaaRXxbLoWh78pQPbIaDiFdcWWRLjSHzSrLyFxbitQ6QMkTSUvM3x6FSANWww

### create a category
PUT {{rillion_HostAddress}}/category
Content-Type: application/json
Authorization: Bearer CfDJ8PvtjQMCay1Fm5RgD3Fa7zZHXFiaHjT6JA-dMNb1x40H8XNueLMeyZ6U2WOEn5u8hEzLOwoHwi28kQoIB6Bt3CrehjVr8l5IQkmSMk8DIFr0HjHRWOyabLpR4nhPMsqxcqZGmG-5nYGZW2dbZLn5PulKbUHbcIsImp8AI_15z6G7lKAxhYTPuEpYxSATkgHVNUcVrhlWVykpFrUPWJV_ul22pXBB_3q61WSzXUN2TNvEJ9sMMlC0FsMFIBbBfTIQssrFBomI9KGq6DN4TjXpsikGjyW8CNLGhhv8JJvtKtQaBA3D_ewx7WE0pCqL1gFwJu8MUVuu3vAecr4j5qMZeumq9dOTHuatOSRL3AO1HeBpLvf_IgEJZpWb1THQq72JNz3Qp1msaNJNTn1W3cDQyU9H2Om8UQIss5iCakAN7c7KLVzlMo-L-XubydeUEzZdOChu_GuEpINFUDN4wRV42a779_6YWSG9gpv_PDjkMjQ6s6l9TsHzHq5Zq4uXfW3X7zCy4lzbXWjpsuCxlzlqYTOgk_GGzWTVlzd_hsZl_9X-0cMmb0dL07ZfeGQQD4YnOOOPbamcwwl7HyCnLdNQ-lbjXG6lhk6xFTlsiD_TKC3eaRPMzxR5mJcMyBlGHMtTe5PBRk4YXJRKNSgg6s87Vis

{
    "Name": "Travel"
}

### update a category
POST {{rillion_HostAddress}}/category
Content-Type: application/json
Authorization: Bearer CfDJ8PvtjQMCay1Fm5RgD3Fa7zaCSQx6becyJuqCF3_th1gNUAJd4kKKUNx1ju10ne0gTUI7K9R7ai9ezt-7JeZV5j_MIBo20F82hOWzP05VuE9BP2MZUCHQwcc9eduQR7EI5yO8vICl9WO8MXDDFPLdPPPIagFhcHdiCxHOkNfmYqFa5ylQsVIrGoBHMTpLGDa4doxqIyWCRqaQkDxnLNOy10bs59a49VzY7ZU8YdEUkYiP4W8t_dea5a55t37h3nQ53ZJgLXhTDNqfRYDhs5QkGhnphNwe0LD9k-JgqvuerP9pfPplgjrGmnymhpCGmCNCibcwhv9eAmKqlTXR3YjZ8mvYhmgo5_g7bcX_idcgU6ETecS-IrG3TnuLaq2vLszyFbAodICWwSQrkkNer5Ni6i-mCBnMe6E28iE4aaIGd1qwVYiJ5fJuB3SLt3Pgf-82Docm20NIX2uhRpoDkv5_0IGaS1az7L23KLU4mTxFd-IgzvYX8dqbS_Yx60mFBiluiv2b_Ozwhrh9oHUTKzDUsR91McwUPAXpVdObDNir0_ZG1MKz9rz0B8dwQPdoOq5HF0nwZ6i066zZwiKwuUGbMWm7g-R_LuAQGGaK1jKOXPSz_HABa61CUCwfsKxgbTv23qaCa_GD3cMswHs-HcBUaes

{
    "Id": 1,
    "Name": "Allowance"
}
