@rillion_HostAddress = http://localhost:5192

### register
POST {{rillion_HostAddress}}/register
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### login
POST {{rillion_HostAddress}}/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### test the token
GET {{rillion_HostAddress}}/manage/info
Authorization: Bearer 

### create a category
PUT {{rillion_HostAddress}}/category
Content-Type: application/json
Authorization: Bearer 

{
    "Name": ""
}

### update a category
POST {{rillion_HostAddress}}/category
Content-Type: application/json
Authorization: Bearer 

{
    "Id": 0,
    "Name": ""
}

### get categories
GET {{rillion_HostAddress}}/category
Authorization: Bearer 

### delete a category
DELETE {{rillion_HostAddress}}/category
Content-Type: application/json
Authorization: Bearer 

{
    "Id": 0
}

### add expense
PUT {{rillion_HostAddress}}/expense
Content-Type: application/json
Authorization: Bearer 

{
    "UserId": 0,
    "Amount": 0,
    "CategoryId": 0,
    "Date": "2024-01-25",
    "Description": ""
}

### get expense
GET {{rillion_HostAddress}}/expense?userId=1&page=0&pageSize=20
Authorization: Bearer 

### update expense amount
POST {{rillion_HostAddress}}/expense/amount
Content-Type: application/json
Authorization: Bearer 

{
    "UserId": 0,
    "Id": 0,
    "Amount": 0
}

### update expense category
POST {{rillion_HostAddress}}/expense/category
Content-Type: application/json
Authorization: Bearer 

{
    "UserId": 0,
    "Id": 0,
    "CategoryId": 0
}